---
include:
  - project: "papers/papers-internal/internal"
    file: "/.base-gitlab-ci.yml"

variables:
  NAMESPACE: "mina-zkoracles"

stages:
  - build
  - publish
  - deploy

build:
  stage: build
  extends: .build
  script:
    - cp $DEPLOYER_PRIVATE_KEY ./contracts/keys/deployer.json
    - !reference [.build, script]

publish-dev:
  stage: publish
  extends: .publish-dev

.deployment_script:
  script:
    # seds
    - find k8s -type f -name \*.yaml -exec sed -i "s|__NAMESPACE_NAME__|"$NAMESPACE"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__TO_BE_REPLACED_BY_IMAGE_TAG__|"$IMAGE_TAG"|g" {} +

    # applying the files
    - kubectl apply -f k8s/common/namespace.yaml
    - kubectl apply -f k8s/common/ --recursive

k8s-deploy-development:
  stage: deploy
  extends: .run_dev
  when: manual
  needs: ["publish-dev"]
  variables:
    IMAGE_TAG: $GOOGLE_TAG_DEV
  script:
    - !reference [.deployment_script, script]
  environment:
    name: development
