---
apiVersion: v1
kind: Secret
metadata:
  name: __NAMESPACE_NAME__-secret
  namespace: __NAMESPACE_NAME__
type: Opaque
stringData:
  DEPLOYER_SECRET_KEY: __DEPLOYER_SECRET_KEY__
  DEPLOYER_PUBLIC_KEY: __DEPLOYER_PUBLIC_KEY__
