apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-oracle
  namespace: __NAMESPACE_NAME__
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 240
      parallelism: 1
      template:
        spec:
          containers:
            - name: update-oracle
              image: __TO_BE_REPLACED_BY_IMAGE_TAG__
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "2048Mi"
                  cpu: "1000m"
                limits:
                  memory: "2048Mi"
                  cpu: "1500m"
          restartPolicy: Never
