apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-oracle
  namespace: __NAMESPACE_NAME__
spec:
  containers:
    - name: app
      image: images.my-company.example/app:v4
      resources:
        requests:
          memory: "1024Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 240
      parallelism: 1
      template:
        spec:
          containers:
            - name: update-oracle
              image: __TO_BE_REPLACED_BY_IMAGE_TAG__
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
